version: '3.2'
services:
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_db:/var/lib/mysql/:rw
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ibm-challenge
volumes:
  mysql_db:
  